---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/frontend/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --production
    - npm run build
    - touch tmp/restart.txt
